new_plotter flexible file extension in phonons.py
materialsproject/atomate2 pull request #624
Opened 2023-11-23 17:18 UTC by JonasGrandel

Before the new_plotter object has always produced `phonon_band_structure.eps` regardless the image format. I and @QuantumChemist made it more flexible using kwargs.

2023-11-27 19:06 UTC, QuantumChemist commented
@utf and @janosh , do you think this little change in the code is ok? 
Thx! :)

2023-11-27 19:18 UTC, janosh requested changes
Sorry, hadn't seen this when I merged https://github.com/materialsproject/atomate2/pull/625 which is why this is now conflicting. I recently removed the `img_format` keyword in pymatgen since it's redundant with the filename.

2023-11-27 23:03 UTC, QuantumChemist commented on src/atomate2/common/schemas/phonons.py
> +            "phonon_band_structure."+kwargs.get("img_format", "eps"),
Ok, I'll let Jonas know tomorrow and he can practice a bit how these things work :)

2024-02-15 09:46 UTC, utf commented
Hi @JonasGrandel and @QuantumChemist what is the status of this PR?

2024-02-15 15:34 UTC, QuantumChemist commented
> Hi @JonasGrandel and @QuantumChemist what is the status of this PR?

I would talk to @JonasGrandel and then come back to you (or we simply finish this PR)!

2024-02-29 09:47 UTC, QuantumChemist commented
> Hi @JonasGrandel and @QuantumChemist what is the status of this PR?

Hi @utf 
I talked to @JonasGrandel and we agreed that I'm going to finish this PR.

2024-04-04 09:48 UTC, closed without merging