Add dir_name to ForceFieldMaker and **task_document_kwargs to rom_ase_compatible_result
materialsproject/atomate2 pull request #791
Opened 2024-03-28 22:52 UTC by QuantumChemist

I need to write the trajectory of a GAPrelax run into a file and then later access the directories of the files. That's why I added dir_name to ForceFieldRelaxMaker and **task_document_kwargs to ForceFieldTaskDocument.from_ase_compatible_result because as far as I can tell, that hasn't been implemented like that yet.

2024-03-29 08:00 UTC, janosh requested changes
perhaps related? https://github.com/materialsproject/jobflow/pull/570

2024-03-29 08:00 UTC, janosh commented on src/atomate2/forcefields/jobs.py
> +            self.task_document_kwargs.update({"dir_name": os.getcwd()})
can be simplified to

```suggestion
        self.task_document_kwargs.setdefault("dir_name", os.getcwd())
```

2024-03-29 09:09 UTC, QuantumChemist commented
> perhaps related? [materialsproject/jobflow#570](https://github.com/materialsproject/jobflow/pull/570)

Having access to `job_dir` would be something handy in general! 
I went with `dir_name` like in other task documents.

2024-04-03 16:23 UTC, QuantumChemist commented
Just wanted to ask if this PR is ok like that, @janosh ? :)

2024-04-03 16:50 UTC, janosh requested changes
apologies, didn't realize this was waiting on me. just 1 minor suggestions re testing

2024-04-03 16:50 UTC, janosh commented on tests/forcefields/test_jobs.py
> +    assert Path(responses[job.uuid][1].output.dir_name).exists()
i think we can move this line to one of the existing tests and avoid having to run another 25 relax steps in CI to keep runtime low

2024-04-03 17:38 UTC, QuantumChemist commented
> apologies, didn't realize this was waiting on me. just 1 minor suggestions re testing

@janosh  no prob at all :) I adjusted the unit test now. I hope this is ok like that!

2024-04-03 17:42 UTC, janosh approved these changes
perfect, thank you!

2024-04-03 20:17 UTC, QuantumChemist commented
@janosh can you please merge it? :) auto merge was disabled and I had to fix merge conflicts with the main branch!

2024-04-04 05:31 UTC, merged